### ISSUE TITLE
Feature request: Support tel and email protocol

### ISSUE THREAD

**Issue by eson57** [Dax89/harbour-webpirate#36]
Hi,

I think tel and email protocol support is essential for any browser, especially for a mobile unit browser, since many mobile sites only use buttons for those features.

**Comment by Dax89** [comment]
Hi,
It was requested here ( https://openrepos.net/comment/5616#comment-5616, maybe you are the author of this comment :D ) 

I have tried but is tricky because I will need to use code not allowed in the harbour.

**Comment by eson57** [comment]
Yes, that was me! Sorry I forgot about it. :)
If the code is not allowed in harbour, how come there is support for both protocols in the Jolla browser?

**Comment by Dax89** [comment]
Jolla Browser uses code not allowed in the harbour because the software is maintained by Jolla itself: if there is any breaking changes in not-allowed APIs they modify their software accordingly.

Currently, the only library that prevents WebPirate to be uploaded in the Harbour is QtSystemInfo.

I can try to do some research and see if I can access to the SailfishOS's dialpad and mail application through D-Bus, and, that, should be allowed in the harbour too.

**Comment by eson57** [comment]
Ok, thanks for taking the time to explain... and trying. Much appreciated.

**Comment by Dax89** [comment]
You're welcome :)
I'll keep this issue open.

**Comment by Dax89** [comment]
I have implemented tel, sms and mailto protocols.

So, they will be available for the next version :)

**Comment by eson57** [comment]
Great news! Thank you!  :)
