### ISSUE TITLE
Screen turns off while watching videos

### ISSUE THREAD

**Issue by carmenfdezb** [Dax89/harbour-webpirate#37]
Is possible to prevent the screen turns off while watching videos? It would be very nice ;)

**Comment by Dax89** [comment]
Mmmmh, this feature is already available:
https://github.com/Dax89/harbour-webpirate/tree/master/src/dbus/client

Implemented in this commit: https://github.com/Dax89/harbour-webpirate/commit/0561d34b8540731ce4f10639580aecf897c66009

It doesn't work anymore? :O

Currently the browser should keep the screen alive *only* when you have selected the tab where the video is playing, otherwise is goes off (maybe this is an unwanted feature)

**Comment by carmenfdezb** [comment]
I watch the videos (for example, from Youtube) in maximized mode. In this case, it's not working for me.

**Comment by Dax89** [comment]
Fixed!

Note: As before, Web Pirate will ping the Jolla every 60 seconds (I don't want to kill your batteries in order to keep the screen alive :D )

I have tested and It works! :)

If the screen goes off again, I will reduce the timer at 30 seconds, but it shouldn't do it (I have tried with long videos and the screen timeout set at 15 seconds)

**Comment by carmenfdezb** [comment]
Great!! Thank you so much!!
